// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/mzhn-sochi/auth-service/internal/config"
)

// Injectors from wire.go:

func Init() (*App, func(), error) {
	configConfig := config.New()
	app := newApp(configConfig)
	return app, func() {
	}, nil
}
