// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"
	"github.com/jmoiron/sqlx"
	"github.com/mzhn-sochi/auth-service/internal/config"
	"github.com/mzhn-sochi/auth-service/internal/handlers/grpc"
	"github.com/mzhn-sochi/auth-service/internal/storage/pg"
	"github.com/mzhn-sochi/auth-service/internal/storage/redis"
	"github.com/mzhn-sochi/auth-service/internal/usecase"
	redis2 "github.com/redis/go-redis/v9"
	"log/slog"
	"os"
	"time"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func Init() (*App, func(), error) {
	configConfig := config.New()
	logger := initLogger(configConfig)
	db, cleanup, err := initDB(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	userStorage := pg.NewUserStorage(db)
	client, cleanup2, err := initRedis(configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenStorage := redis.NewTokenStorage(configConfig, client)
	useCase := usecase.New(configConfig, userStorage, tokenStorage)
	server := grpc.New(configConfig, useCase, useCase)
	app := newApp(configConfig, logger, server)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func initLogger(cfg *config.Config) *slog.Logger {

	var level slog.Level

	switch cfg.Logger.Level {
	case "debug":
		level = slog.LevelDebug
	case "info":
		level = slog.LevelInfo
	}

	return slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: level}))
}

func initDB(cfg *config.Config, log *slog.Logger) (*sqlx.DB, func(), error) {

	host := cfg.DB.Host
	port := cfg.DB.Port
	user := cfg.DB.User
	pass := cfg.DB.Pass
	name := cfg.DB.Name

	cs := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable", user, pass, host, port, name)

	log.Info("connecting to database", slog.String("conn", cs))

	db, err := sqlx.Open("postgres", cs)
	if err != nil {
		return nil, nil, err
	}

	if err := db.Ping(); err != nil {
		log.Error("failed to connect to database", slog.String("err", err.Error()), slog.String("conn", cs))
		return nil, func() { db.Close() }, err
	}

	log.Info("connected to database", slog.String("conn", cs))

	return db, func() { db.Close() }, nil
}

func initRedis(cfg *config.Config, log *slog.Logger) (*redis2.Client, func(), error) {
	host := cfg.Redis.Host
	port := cfg.Redis.Port
	pass := cfg.Redis.Pass
	db := cfg.Redis.DB

	client := redis2.NewClient(&redis2.Options{
		Addr:     fmt.Sprintf("%s:%d", host, port),
		Password: pass,
		DB:       db,
	})

	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)

	log.Info("connecting to redis", slog.Int("db", db), slog.String("host", host), slog.Int("port", port))

	if _, err := client.Ping(ctx).Result(); err != nil {
		log.Error("failed to connect to redis", slog.String("err", err.Error()), slog.Int("db", db), slog.String("host", host), slog.Int("port", port))
		return nil, func() { client.Close() }, err
	}

	log.Info("connected to redis", slog.Int("db", db), slog.String("host", host), slog.Int("port", port))

	return client, func() { client.Close() }, nil
}
